github:
  description: Source of Apache ECharts website
  homepage:
  labels:
    - echarts
    - apache
    - website

notifications:
  commits: commits@echarts.apache.org
  pullrequests: commits@echarts.apache.org
  issues: commits@echarts.apache.org
